spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: 3168
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: bluepal
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  
server :
    port : 4041  

planapi:
   messages:
      planSaveSucc : Plan Saved Successfully
      planSaveFail   : Plan Saved Failed
      planUpdateSucc : Plan Updated Successfully
      planUpdateFail   : Plan Updated Failed
      planDeleteSucc : Plan Deleted SuccessFully
      planDeleteFail : Plan Deleted Failed
      planStatusChangeSucc : Plan Status Changed Successfully
      planStatusChangeFail : Plan Status Changed Failed
